on:
  push:
    tags:
    - '*'

permissions:
  contents: write
  discussions: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: hostwithquantum/action-gh-release@fix-failure
